server:
  port: 9001

sp:
  jwt:
    secret: auth-server-1
    token-life-time: 100
    token-refresh-time: 10000

spring:
  data:
    mongodb:
      database: auth-server-1
      host: localhost
      port: 27017

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    #    org.springframework.boot.autoconfigure: DEBUG
    com.sp.sec: DEBUG
