server:
  port: 9000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    #    org.springframework.boot.autoconfigure: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    #    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.hibernate.SQL: DEBUG
    #    org.hibernate.SQL.type.descriptor.sql.BasicBinder: TRACE
    com.example: DEBUG

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create
    show-sql: true


