server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 108050356439-ah0csttecetisk4q4pa0777de6kf0quf.apps.googleusercontent.com
            client-secret: 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
          facebook:
            client-id: 488695445381590
            client-secret: bcbbc8a3a1d98bedeb258b318878e745
          kakao:
            client-id: 050cc30618bf0988f3d82f6c620f85b8
            client-secert: xMksiOIxLOMgCVDh8g8wH97IQ2fSLjs1
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            client-name: kakao
          naver:
            client-id: OVtjSYcQ2dHY2RPHSmIH
            client-secret: SrR8XPUPl1
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            client-name: naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    #    org.springframework.boot.autoconfigure: DEBUG
    com.sp.sec: DEBUG
