server:
  port: 9000

logging:
  #  pattern:
  #    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    #    org.springframework.boot.autoconfigure: DEBUG
    com.example: DEBUG
