server:
  port: 8080
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 108050356439-ah0csttecetisk4q4pa0777de6kf0quf.apps.googleusercontent.com
            client-secret: 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
  #            client-id: 377825014181-2tpha7niq0hjar86e4j8h6dl0h8j1s3i.apps.googleusercontent.com
  #            client-secret: yyHXhXWBRrx3jyDWrhiSwzu8
  data:
    mongodb:
      database: google-client
      host: localhost
      port: 27017

#http://localhost:8080/auth/realms/company-services/broker/google/endpoint
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    #    org.springframework.boot.autoconfigure: DEBUG
    com.sp.sec: DEBUG


